sonar.projectKey=qa-app
sonar.projectName=QA Application
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Host configuration
sonar.host.url=http://localhost:9000

# Sources
sonar.sources=src,server
sonar.tests=tests

# Language
sonar.language=js
sonar.javascript.node.maxspace=4096

# Coverage information
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Token authentication
# sonar.login=sqa_99a5c482826ccfebf6bfcd0b00af391843d2cb67